### ISSUE TITLE
Please add '-fsigned-char' into the CFLAGS

### ISSUE THREAD

**Issue by ghost** [cisco/usnic_tools#13]
The gcc option, '-fsigned-char', is necessary to build usnic-tools over ARM platform. So, please ensure it as default CFLAGS. 

https://kojipkgs.fedoraproject.org//work/tasks/9718/13659718/build.log

```
config.status: executing depfiles commands
config.status: executing libtool commands
+ make -j4 V=1
gcc -DPACKAGE_NAME=\"usnic-tools\" -DPACKAGE_TARNAME=\"usnic-tools\" -DPACKAGE_VERSION=\"1.1.0.0\" -DPACKAGE_STRING=\"usnic-tools\ 1.1.0.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBFABRIC=1 -DSTDC_HEADERS=1 -I.    -g -Wall -Werror -Wextra -pedantic -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard -c -o usnic_devinfo.o usnic_devinfo.c
usnic_devinfo.c: In function 'main':
usnic_devinfo.c:177:41: error: comparison is always true due to limited range of data type [-Werror=type-limits]
  while ((c = getopt(argc, argv, "bd:")) != EOF) {
                                         ^~
cc1: all warnings being treated as errors
Makefile:460: recipe for target 'usnic_devinfo.o' failed
make: *** [usnic_devinfo.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.AkEWI1 (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.AkEWI1 (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 88, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/util.py", line 547, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target armv7hl --nodeps /builddir/build/SPECS/usnic-tools.spec
```

**EDIT:** Use Markdown wiki format

**Comment by michich** [comment]
In https://bugzilla.redhat.com/show_bug.cgi?id=1327083#c5 I suggested a better fix:

This is because of this code:

```
  char c;
  /* ... */
  while ((c = getopt(argc, argv, "bd:")) != EOF) { /* ... */ }
```

A better fix is to have `c` as `int`.

Also, `getopt()` is specified to return -1, not `EOF`, when all options have been parsed. On glibc `EOF` is -1, but it should not be relied on.

**Comment by jsquyres** [comment]
@HonggangLI New release fixes the issue: https://github.com/cisco/usnic_tools/releases/tag/v1.1.1.0
